#!/bin/sh

# Creates a set of test sequences from the template images that are
# used in the unit tests. 

# GIF     2     2      index/test1.#.gif      1-4
mkdir -p index
cp templateImages/2x2.gif index/test1.0001.gif
cp templateImages/2x2.gif index/test1.0002.gif
cp templateImages/2x2.gif index/test1.0003.gif
cp templateImages/2x2.gif index/test1.0004.gif

# GIF		4	4		index/test1.#.gif					5
mkdir -p index
cp templateImages/4x4.gif index/test1.0005.gif

# SGI		8	8		index/test2.@@					8
mkdir -p index
cp templateImages/8x8.sgi index/test2.08

# Cineon	4	4		test/index/foo/#					2-3
mkdir -p index/foo
cp templateImages/4x4.cin index/foo/0002
cp templateImages/4x4.cin index/foo/0003

# Cineon	8	8		index/blah/a/#.cin				6-7
mkdir -p index/blah/a
cp templateImages/8x8.cin index/blah/a/0006.cin
cp templateImages/8x8.cin index/blah/a/0007.cin

# GIF		2	2		seq/test1.#.gif						1-4
mkdir -p seq
cp templateImages/2x2.gif seq/test1.0001.gif
cp templateImages/2x2.gif seq/test1.0002.gif
cp templateImages/2x2.gif seq/test1.0003.gif
cp templateImages/2x2.gif seq/test1.0004.gif

# GIF		2	2		seq/test2.@.gif						8
mkdir -p seq
cp templateImages/2x2.gif seq/test2.8.gif

# GIF		2	2		seq/test2.@@@@@@.gif	123
mkdir -p seq
cp templateImages/2x2.gif seq/test2.000123.gif

# GIF		2	2		seq/@@@.gif						120
mkdir -p seq
cp templateImages/2x2.gif seq/120.gif

# TIFF		4	4		seq/@@@.gif						110
mkdir -p seq
cp templateImages/4x4.tiff seq/110.gif

# Cineon	8	8		seq/test3.#							1,3
mkdir -p seq
cp templateImages/8x8.cin seq/test3.0001
cp templateImages/8x8.cin seq/test3.0003

# Cineon INVALID	seq/test3.#						2,4
mkdir -p seq
cp templateImages/8x8.cin-invalid seq/test3.0002
cp templateImages/8x8.cin-invalid seq/test3.0004

# Cineon	8	8		seq/foo
mkdir -p seq
cp templateImages/8x8.cin seq/foo

# Cineon	8	8		seq/bar
mkdir -p seq
cp templateImages/8x8.cin seq/bar

