# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "file_info", :force => true do |t|
    t.column "path", :text
    t.column "name", :text
    t.column "modified", :datetime
    t.column "size", :integer, :limit => 15
  end

end
